apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapiapp.fullname" . }}-db
  labels:
    {{- include "fastapiapp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fastapiapp.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "fastapiapp.fullname" . }}-db
    spec:
      containers:
        - name: postgres
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.database.name | quote }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          emptyDir: {}